### ISSUE TITLE
[🚨Bug] 로그인시 Home 화면 렌더링 문제 (👀확인 부탁드립니다!)

### ISSUE THREAD

**Issue by Sooooyeon** [FRONTENDSCHOOL7/final-18-moamoa#282]
📌 이슈 내용
------------
로그아웃 후 다른 계정으로 로그인 하면 이전 사용자가 팔로우 하는 유저의 게시글이 렌더링되는 문제가 있습니다.

📝 작업 내용
------------
vscode 중단점을 사용해 디버깅해보는 방법이 있다는 것을 듣고 시도해보던중 디버깅을 위해 새로 열린 브라우저 창에서는 렌더링 문제 없이 잘 동작하는 것을 확인했습니다. 다른 브라우저와 크롬 시크릿모드로 실행해보니 마찬가지로 정상 작동 됩니다. 따라서 코드 문제가 아닌 캐시문제로 판단되어 크롬 브라우저 캐시를 삭제했더니 렌더링 문제가 사라졌습니다.

✨ 참고 사항
------------
번거로우시겠지만 크롬 브라우저에서 캐시 삭제 후 재실행 부탁드리겠습니다. 
@timetam24 @AYFG @LeeeeHaeji  캐시 삭제해도 같은 문제가 발생된다면 코멘트 부탁드리겠습니다.
감사합니다.

**Comment by Sooooyeon** [comment]
@timetam24 @AYFG @LeeeeHaeji 확인 부탁드립니다!

**Comment by timetam24** [comment]
확인했습니다! 저는 캐시 삭제 후 처음 실행했을 때는 문제 없이 작동하는데
브라우저 종료 후 다시 프로젝트를 시작했을 때 같은 문제가 발생하고 있습니다🥲

**Comment by Sooooyeon** [comment]
> 확인했습니다! 저는 캐시 삭제 후 처음 실행했을 때는 문제 없이 작동하는데 브라우저 종료 후 다시 프로젝트를 시작했을 때 같은 문제가 발생하고 있습니다🥲

브라우저 창이 닫힐 때 기존 데이터가 지워지게하는 방법을 찾아보겠습니다! 확인 감사합니다 : )

**Comment by LeeeeHaeji** [comment]
늦게 확인해서 죄송합니다! 저도 의진님과 마찬가지로 브라우저 종료 후 다시 프로젝트를 시작했을때 말씀하신 문제가 발생하고 있습니다! 
 여기서 추가로 확인해보니 로그아웃 후 다른 계정으로 로그인하면 이전 사용자가 팔로우 하는 유저의 게시글이 나올뿐만 아니라 프로필 상세 페이지도 이전 사용자의 프로필 상세 페이지가 나타나는 문제가 발생하는것같습니다! 한번 새로고침을 하면 로그인한 사용자의 프로필 상세페이지로 돌아옵니다!
