### ISSUE TITLE
[🚨Bug]상품리스트 이미지 렌더링 안되는 오류 수정

### ISSUE THREAD

**Issue by AYFG** [FRONTENDSCHOOL7/final-18-moamoa#87]
📌 이슈 내용
------------
다른 조원들의 product/list 에 상품의 이미지가 렌더링되지 않는 오류 해결하겠습니다.

📝 작업 내용
------------
- [ ] 작업 1
- [ ] 작업 2

✨ 참고 사항
------------

**Comment by Sooooyeon** [comment]
재웅님 어떤 도움이 필요하신가요!!?
